// single
export const FETCHED_ALL_PROJECT_DATA = 'FETCHED_ALL_PROJECT_DATA'
export const FETCHED_ALL_TECH_DATA = 'FETCHED_ALL_TECH_DATA'
export const SELECTED_PROJECT = 'SELECTED_PROJECT'
export const SELECTED_TECH = 'SELECTED_TECH'
export const SELECTED_SUBJECT = 'SELECTED_SUBJECT'
export const SET_FLEX_DIR_OF_CONTENT_DETAILS = 'SET_FLEX_DIR_OF_CONTENT_DETAILS'
export const NAV_ON_MOBILE_PRESENT = 'NAV_ON_MOBILE_PRESENT'
export const TOGGLE_IMAGE_MODAL = 'TOGGLE_IMAGE_MODAL'
export const MODAL_IMAGE_SELECTED = 'MODAL_IMAGE_SELECTED'
export const TOGGLE_DETAILS_SECTION_MOBILE = 'TOGGLE_DETAILS_SECTION_MOBILE'

// 2 or more
export const OPEN_CONTENT_DETAILS = 'OPEN_CONTENT_DETAILS'
export const CLOSE_CONTENT_DETAILS = 'CLOSE_CONTENT_DETAILS'

export const TOGGLE_CONTENT_DETAILS_SECTION = 'TOGGLE_CONTENT_DETAILS_SECTION'
export const CLOSE_CONTENT_DETAILS_SECTION = 'CLOSE_CONTENT_DETAILS_SECTION'

export const UPDATE_CONTACT_PAGE_RENDER = 'UPDATE_CONTACT_PAGE_RENDER'
export const UPDATE_TECH_PAGE_RENDER = 'UPDATE_TECH_PAGE_RENDER'
export const UPDATE_PROJECTS_PAGE_RENDER = 'UPDATE_PROJECTS_PAGE_RENDER'